// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emlqoukusybddgxihelc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtbHFvdWt1c3liZGRneGloZWxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTg5NDgsImV4cCI6MjA2MDczNDk0OH0.QFYyP1rgP8-e5h0yRGB4iIerZ5Pkdzxnbe3BtVqfwGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);